// Code generated by mockery v2.53.5. DO NOT EDIT.

package plugins

import (
	mock "github.com/stretchr/testify/mock"

	plugins "github.com/crd2go/openapi2crd/pkg/plugins"
)

// PropertyPluginMock is an autogenerated mock type for the PropertyPlugin type
type PropertyPluginMock[R interface{}] struct {
	mock.Mock
}

type PropertyPluginMock_Expecter[R interface{}] struct {
	mock *mock.Mock
}

func (_m *PropertyPluginMock[R]) EXPECT() *PropertyPluginMock_Expecter[R] {
	return &PropertyPluginMock_Expecter[R]{mock: &_m.Mock}
}

// Name provides a mock function with no fields
func (_m *PropertyPluginMock[R]) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// PropertyPluginMock_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type PropertyPluginMock_Name_Call[R interface{}] struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *PropertyPluginMock_Expecter[R]) Name() *PropertyPluginMock_Name_Call[R] {
	return &PropertyPluginMock_Name_Call[R]{Call: _e.mock.On("Name")}
}

func (_c *PropertyPluginMock_Name_Call[R]) Run(run func()) *PropertyPluginMock_Name_Call[R] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PropertyPluginMock_Name_Call[R]) Return(_a0 string) *PropertyPluginMock_Name_Call[R] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PropertyPluginMock_Name_Call[R]) RunAndReturn(run func() string) *PropertyPluginMock_Name_Call[R] {
	_c.Call.Return(run)
	return _c
}

// Process provides a mock function with given fields: request
func (_m *PropertyPluginMock[R]) Process(request *plugins.PropertyProcessorRequest) error {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*plugins.PropertyProcessorRequest) error); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PropertyPluginMock_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type PropertyPluginMock_Process_Call[R interface{}] struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - request *plugins.PropertyProcessorRequest
func (_e *PropertyPluginMock_Expecter[R]) Process(request interface{}) *PropertyPluginMock_Process_Call[R] {
	return &PropertyPluginMock_Process_Call[R]{Call: _e.mock.On("Process", request)}
}

func (_c *PropertyPluginMock_Process_Call[R]) Run(run func(request *plugins.PropertyProcessorRequest)) *PropertyPluginMock_Process_Call[R] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*plugins.PropertyProcessorRequest))
	})
	return _c
}

func (_c *PropertyPluginMock_Process_Call[R]) Return(_a0 error) *PropertyPluginMock_Process_Call[R] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PropertyPluginMock_Process_Call[R]) RunAndReturn(run func(*plugins.PropertyProcessorRequest) error) *PropertyPluginMock_Process_Call[R] {
	_c.Call.Return(run)
	return _c
}

// NewPropertyPluginMock creates a new instance of PropertyPluginMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPropertyPluginMock[R interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *PropertyPluginMock[R] {
	mock := &PropertyPluginMock[R]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
