// Code generated by mockery v2.53.5. DO NOT EDIT.

package config

import (
	context "context"

	openapi3 "github.com/getkin/kin-openapi/openapi3"
	mock "github.com/stretchr/testify/mock"

	v1alpha1 "github.com/crd2go/openapi2crd/pkg/apis/config/v1alpha1"
)

// LoaderMock is an autogenerated mock type for the Loader type
type LoaderMock struct {
	mock.Mock
}

type LoaderMock_Expecter struct {
	mock *mock.Mock
}

func (_m *LoaderMock) EXPECT() *LoaderMock_Expecter {
	return &LoaderMock_Expecter{mock: &_m.Mock}
}

// Load provides a mock function with given fields: ctx, def
func (_m *LoaderMock) Load(ctx context.Context, def v1alpha1.OpenAPIDefinition) (*openapi3.T, error) {
	ret := _m.Called(ctx, def)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *openapi3.T
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, v1alpha1.OpenAPIDefinition) (*openapi3.T, error)); ok {
		return rf(ctx, def)
	}
	if rf, ok := ret.Get(0).(func(context.Context, v1alpha1.OpenAPIDefinition) *openapi3.T); ok {
		r0 = rf(ctx, def)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*openapi3.T)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, v1alpha1.OpenAPIDefinition) error); ok {
		r1 = rf(ctx, def)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoaderMock_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type LoaderMock_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - def v1alpha1.OpenAPIDefinition
func (_e *LoaderMock_Expecter) Load(ctx interface{}, def interface{}) *LoaderMock_Load_Call {
	return &LoaderMock_Load_Call{Call: _e.mock.On("Load", ctx, def)}
}

func (_c *LoaderMock_Load_Call) Run(run func(ctx context.Context, def v1alpha1.OpenAPIDefinition)) *LoaderMock_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1alpha1.OpenAPIDefinition))
	})
	return _c
}

func (_c *LoaderMock_Load_Call) Return(_a0 *openapi3.T, _a1 error) *LoaderMock_Load_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LoaderMock_Load_Call) RunAndReturn(run func(context.Context, v1alpha1.OpenAPIDefinition) (*openapi3.T, error)) *LoaderMock_Load_Call {
	_c.Call.Return(run)
	return _c
}

// NewLoaderMock creates a new instance of LoaderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoaderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoaderMock {
	mock := &LoaderMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
